In [2]:
%pip install dask[dataframe] -q
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)

Note: you may need to restart the kernel to use updated packages.

# Step1. Processing cox-violent-parsed datasets

In [3]:
cvp_df = pd.read_csv('datasets/cox-violent-parsed_filt.csv')
cvpt_df = pd.read_csv('datasets/cox-violent-parsed_filt_transformed.csv') # Contains a column for income in place of sex column in cvp_df

## Adding the income column to cvp_df
cvp_df['income'] = cvpt_df['income'].values

In [4]:
print(cvp_df.shape)
cvp_df.head(10)

(18316, 41)

,id,name,first,last,sex,dob,age,age_cat,race,juv_fel_count,decile_score,juv_misd_count,juv_other_count,priors_count,days_b_screening_arrest,c_jail_in,c_jail_out,c_days_from_compas,c_charge_degree,c_charge_desc,is_recid,r_charge_degree,r_days_from_arrest,r_offense_date,r_charge_desc,r_jail_in,violent_recid,is_violent_recid,vr_charge_degree,vr_offense_date,vr_charge_desc,type_of_assessment,decile_score.1,score_text,screening_date,v_type_of_assessment,v_decile_score,v_score_text,priors_count.1,event,income
0,1.0,miguel hernandez,miguel,hernandez,Male,18/04/1947,69,Greater than 45,Other,0,1,0,0,0,-1.0,13/08/2013 6:03,14/08/2013 5:41,1.0,(F3),Aggravated Assault w/Firearm,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,Risk of Recidivism,1,Low,14/08/2013,Risk of Violence,1,Low,0,0,Lower
1,2.0,miguel hernandez,miguel,hernandez,Male,18/04/1947,69,Greater than 45,Other,0,1,0,0,0,-1.0,13/08/2013 6:03,14/08/2013 5:41,1.0,(F3),Aggravated Assault w/Firearm,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,Risk of Recidivism,1,Low,14/08/2013,Risk of Violence,1,Low,0,0,Lower
2,3.0,michael ryan,michael,ryan,Male,06/02/1985,31,25 - 45,Caucasian,0,5,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,-1,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,Risk of Recidivism,5,Medium,31/12/2014,Risk of Violence,2,Low,0,0,Lower
3,4.0,kevon dixon,kevon,dixon,Male,22/01/1982,34,25 - 45,African-American,0,3,0,0,0,-1.0,26/01/2013 3:45,05/02/2013 5:36,1.0,(F3),Felony Battery w/Prior Convict,1,(F3),NaN,05/07/2013,Felony Battery (Dom Strang),NaN,NaN,1,(F3),05/07/2013,Felony Battery (Dom Strang),Risk of Recidivism,3,Low,27/01/2013,Risk of Violence,1,Low,0,1,Lower
4,5.0,ed philo,ed,philo,Male,14/05/1991,24,Less than 25,African-American,0,4,0,1,4,-1.0,13/04/2013 4:58,14/04/2013 7:02,1.0,(F3),Possession of Cocaine,1,(M1),0.0,16/06/2013,Driving Under The Influence,16/06/2013,NaN,0,NaN,NaN,NaN,Risk of Recidivism,4,Low,14/04/2013,Risk of Violence,3,Low,4,0,Lower
5,6.0,ed philo,ed,philo,Male,14/05/1991,24,Less than 25,African-American,0,4,0,1,4,-1.0,13/04/2013 4:58,14/04/2013 7:02,1.0,(F3),Possession of Cocaine,1,(M1),0.0,16/06/2013,Driving Under The Influence,16/06/2013,NaN,0,NaN,NaN,NaN,Risk of Recidivism,4,Low,14/04/2013,Risk of Violence,3,Low,4,0,Lower
6,7.0,ed philo,ed,philo,Male,14/05/1991,24,Less than 25,African-American,0,4,0,1,4,-1.0,13/04/2013 4:58,14/04/2013 7:02,1.0,(F3),Possession of Cocaine,1,(M1),0.0,16/06/2013,Driving Under The Influence,16/06/2013,NaN,0,NaN,NaN,NaN,Risk of Recidivism,4,Low,14/04/2013,Risk of Violence,3,Low,4,0,Lower
7,8.0,ed philo,ed,philo,Male,14/05/1991,24,Less than 25,African-American,0,4,0,1,4,-1.0,13/04/2013 4:58,14/04/2013 7:02,1.0,(F3),Possession of Cocaine,1,(M1),0.0,16/06/2013,Driving Under The Influence,16/06/2013,NaN,0,NaN,NaN,NaN,Risk of Recidivism,4,Low,14/04/2013,Risk of Violence,3,Low,4,0,Lower
8,9.0,ed philo,ed,philo,Male,14/05/1991,24,Less than 25,African-American,0,4,0,1,4,-1.0,13/04/2013 4:58,14/04/2013 7:02,1.0,(F3),Possession of Cocaine,1,(M1),0.0,16/06/2013,Driving Under The Influence,16/06/2013,NaN,0,NaN,NaN,NaN,Risk of Recidivism,4,Low,14/04/2013,Risk of Violence,3,Low,4,0,Lower
9,10.0,marcu brown,marcu,brown,Male,21/01/1993,23,Less than 25,African-American,0,8,1,0,1,NaN,NaN,NaN,1.0,(F3),Possession of Cannabis,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,Risk of Recidivism,8,High,13/01/2013,Risk of Violence,6,Medium,1,0,Lower

In [5]:
cvp_df.drop('id', axis=1, inplace=True)
cvp_df = cvp_df.drop_duplicates()
print(cvp_df.shape)
cvp_df.head(10)

(11300, 40)

,name,first,last,sex,dob,age,age_cat,race,juv_fel_count,decile_score,juv_misd_count,juv_other_count,priors_count,days_b_screening_arrest,c_jail_in,c_jail_out,c_days_from_compas,c_charge_degree,c_charge_desc,is_recid,r_charge_degree,r_days_from_arrest,r_offense_date,r_charge_desc,r_jail_in,violent_recid,is_violent_recid,vr_charge_degree,vr_offense_date,vr_charge_desc,type_of_assessment,decile_score.1,score_text,screening_date,v_type_of_assessment,v_decile_score,v_score_text,priors_count.1,event,income
0,miguel hernandez,miguel,hernandez,Male,18/04/1947,69,Greater than 45,Other,0,1,0,0,0,-1.0,13/08/2013 6:03,14/08/2013 5:41,1.0,(F3),Aggravated Assault w/Firearm,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,Risk of Recidivism,1,Low,14/08/2013,Risk of Violence,1,Low,0,0,Lower
2,michael ryan,michael,ryan,Male,06/02/1985,31,25 - 45,Caucasian,0,5,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,-1,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,Risk of Recidivism,5,Medium,31/12/2014,Risk of Violence,2,Low,0,0,Lower
3,kevon dixon,kevon,dixon,Male,22/01/1982,34,25 - 45,African-American,0,3,0,0,0,-1.0,26/01/2013 3:45,05/02/2013 5:36,1.0,(F3),Felony Battery w/Prior Convict,1,(F3),NaN,05/07/2013,Felony Battery (Dom Strang),NaN,NaN,1,(F3),05/07/2013,Felony Battery (Dom Strang),Risk of Recidivism,3,Low,27/01/2013,Risk of Violence,1,Low,0,1,Lower
4,ed philo,ed,philo,Male,14/05/1991,24,Less than 25,African-American,0,4,0,1,4,-1.0,13/04/2013 4:58,14/04/2013 7:02,1.0,(F3),Possession of Cocaine,1,(M1),0.0,16/06/2013,Driving Under The Influence,16/06/2013,NaN,0,NaN,NaN,NaN,Risk of Recidivism,4,Low,14/04/2013,Risk of Violence,3,Low,4,0,Lower
9,marcu brown,marcu,brown,Male,21/01/1993,23,Less than 25,African-American,0,8,1,0,1,NaN,NaN,NaN,1.0,(F3),Possession of Cannabis,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,Risk of Recidivism,8,High,13/01/2013,Risk of Violence,6,Medium,1,0,Lower
10,bouthy pierrelouis,bouthy,pierrelouis,Male,22/01/1973,43,25 - 45,Other,0,1,0,0,2,NaN,NaN,NaN,76.0,(F7),arrest case no charge,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,Risk of Recidivism,1,Low,26/03/2013,Risk of Violence,1,Low,2,0,Lower
11,marsha miles,marsha,miles,Male,22/08/1971,44,25 - 45,Other,0,1,0,0,0,0.0,30/11/2013 4:50,01/12/2013 12:28,0.0,(M1),Battery,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,Risk of Recidivism,1,Low,30/11/2013,Risk of Violence,1,Low,0,0,Lower
12,edward riddle,edward,riddle,Male,23/07/1974,41,25 - 45,Caucasian,0,6,0,0,14,-1.0,18/02/2014 5:08,24/02/2014 12:18,1.0,(F3),Possession Burglary Tools,1,(F2),0.0,31/03/2014,Poss of Firearm by Convic Felo,31/03/2014,NaN,0,NaN,NaN,NaN,Risk of Recidivism,6,Medium,19/02/2014,Risk of Violence,2,Low,14,0,Lower
14,steven stewart,steven,stewart,Male,25/02/1973,43,25 - 45,Other,0,4,0,0,3,-1.0,29/08/2013 8:55,30/08/2013 8:42,1.0,(F3),arrest case no charge,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,Risk of Recidivism,4,Low,30/08/2013,Risk of Violence,3,Low,3,0,Lower
17,elizabeth thieme,elizabeth,thieme,Female,03/06/1976,39,25 - 45,Caucasian,0,1,0,0,0,-1.0,15/03/2014 5:35,18/03/2014 4:28,1.0,(M1),Battery,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,Risk of Recidivism,1,Low,16/03/2014,Risk of Violence,1,Low,0,0,Higher

### Dropping unuseful features

In [6]:
## Dropping unuseful and repetitive columns, but keeping first(name), last(name), and dob for joining the datasets later
cvp_df.drop(['name','age_cat','c_days_from_compas','violent_recid','type_of_assessment','v_type_of_assessment',
             'c_charge_desc', 'r_charge_desc', 'vr_charge_desc', 'decile_score.1', 'priors_count.1',], axis=1, inplace=True)

## Dropping 'race' column. Use the next line instead to keep the race in another version for a comparison.
cvp_df.drop('race', axis=1, inplace=True)
#cvp_df = pd.get_dummies(cvp_df, columns=['race'], drop_first=False)

## Replacing jail in/out with jail duration
cvp_df['c_jail_in'] = pd.to_datetime(cvp_df['c_jail_in'], dayfirst=True)
cvp_df['c_jail_out'] = pd.to_datetime(cvp_df['c_jail_out'], dayfirst=True)
cvp_df['jail_duration'] = (cvp_df['c_jail_out'] - cvp_df['c_jail_in']).dt.days
cvp_df.drop(['c_jail_in', 'c_jail_out'], axis=1, inplace=True)

In [7]:
print(cvp_df.shape)
cvp_df.head(10)

(11300, 27)

,first,last,sex,dob,age,juv_fel_count,decile_score,juv_misd_count,juv_other_count,priors_count,days_b_screening_arrest,c_charge_degree,is_recid,r_charge_degree,r_days_from_arrest,r_offense_date,r_jail_in,is_violent_recid,vr_charge_degree,vr_offense_date,score_text,screening_date,v_decile_score,v_score_text,event,income,jail_duration
0,miguel,hernandez,Male,18/04/1947,69,0,1,0,0,0,-1.0,(F3),0,NaN,NaN,NaN,NaN,0,NaN,NaN,Low,14/08/2013,1,Low,0,Lower,0.0
2,michael,ryan,Male,06/02/1985,31,0,5,0,0,0,NaN,NaN,-1,NaN,NaN,NaN,NaN,0,NaN,NaN,Medium,31/12/2014,2,Low,0,Lower,NaN
3,kevon,dixon,Male,22/01/1982,34,0,3,0,0,0,-1.0,(F3),1,(F3),NaN,05/07/2013,NaN,1,(F3),05/07/2013,Low,27/01/2013,1,Low,1,Lower,10.0
4,ed,philo,Male,14/05/1991,24,0,4,0,1,4,-1.0,(F3),1,(M1),0.0,16/06/2013,16/06/2013,0,NaN,NaN,Low,14/04/2013,3,Low,0,Lower,1.0
9,marcu,brown,Male,21/01/1993,23,0,8,1,0,1,NaN,(F3),0,NaN,NaN,NaN,NaN,0,NaN,NaN,High,13/01/2013,6,Medium,0,Lower,NaN
10,bouthy,pierrelouis,Male,22/01/1973,43,0,1,0,0,2,NaN,(F7),0,NaN,NaN,NaN,NaN,0,NaN,NaN,Low,26/03/2013,1,Low,0,Lower,NaN
11,marsha,miles,Male,22/08/1971,44,0,1,0,0,0,0.0,(M1),0,NaN,NaN,NaN,NaN,0,NaN,NaN,Low,30/11/2013,1,Low,0,Lower,1.0
12,edward,riddle,Male,23/07/1974,41,0,6,0,0,14,-1.0,(F3),1,(F2),0.0,31/03/2014,31/03/2014,0,NaN,NaN,Medium,19/02/2014,2,Low,0,Lower,6.0
14,steven,stewart,Male,25/02/1973,43,0,4,0,0,3,-1.0,(F3),0,NaN,NaN,NaN,NaN,0,NaN,NaN,Low,30/08/2013,3,Low,0,Lower,0.0
17,elizabeth,thieme,Female,03/06/1976,39,0,1,0,0,0,-1.0,(M1),0,NaN,NaN,NaN,NaN,0,NaN,NaN,Low,16/03/2014,1,Low,0,Higher,2.0

### Converting categorical scale variables to nummerical values

In [8]:
## Assigning numerical values to represent the intensity of different charge degrees.
charge_degree_mapping = {'(M1)': 1, '(M2)': 2, '(MO3)': 3, '(F1)': 6, '(F2)': 8, '(F3)': 10, '(F5)': 12, '(F6)': 14, '(F7)': 16}
cvp_df['c_charge_degree'] = cvp_df['c_charge_degree'].map(charge_degree_mapping)
cvp_df['r_charge_degree'] = cvp_df['r_charge_degree'].map(charge_degree_mapping)
cvp_df['vr_charge_degree'] = cvp_df['vr_charge_degree'].map(charge_degree_mapping)

### Converting to correct formats and some cleaning

In [9]:
## Converting date columns to datetime format
cvp_df['dob'] = pd.to_datetime(cvp_df['dob'], dayfirst=True)
cvp_df['r_offense_date'] = pd.to_datetime(cvp_df['r_offense_date'], dayfirst=True)
cvp_df['r_jail_in'] = pd.to_datetime(cvp_df['r_jail_in'], dayfirst=True)
cvp_df['vr_offense_date'] = pd.to_datetime(cvp_df['vr_offense_date'], dayfirst=True)
cvp_df['screening_date'] = pd.to_datetime(cvp_df['screening_date'], dayfirst=True)

## Replacing -1s with nan in event and is_recid
cvp_df['event'] = cvp_df['event'].replace(-1, np.nan)
cvp_df['is_recid'] = cvp_df['is_recid'].replace(-1, np.nan)

cvp_df['first'] = cvp_df['first'].str.lower()
cvp_df['last'] = cvp_df['last'].str.lower()

In [10]:
cvp_df.head(8)

,first,last,sex,dob,age,juv_fel_count,decile_score,juv_misd_count,juv_other_count,priors_count,days_b_screening_arrest,c_charge_degree,is_recid,r_charge_degree,r_days_from_arrest,r_offense_date,r_jail_in,is_violent_recid,vr_charge_degree,vr_offense_date,score_text,screening_date,v_decile_score,v_score_text,event,income,jail_duration
0,miguel,hernandez,Male,1947-04-18,69,0,1,0,0,0,-1.0,10.0,0.0,NaN,NaN,NaT,NaT,0,NaN,NaT,Low,2013-08-14,1,Low,0,Lower,0.0
2,michael,ryan,Male,1985-02-06,31,0,5,0,0,0,NaN,NaN,NaN,NaN,NaN,NaT,NaT,0,NaN,NaT,Medium,2014-12-31,2,Low,0,Lower,NaN
3,kevon,dixon,Male,1982-01-22,34,0,3,0,0,0,-1.0,10.0,1.0,10.0,NaN,2013-07-05,NaT,1,10.0,2013-07-05,Low,2013-01-27,1,Low,1,Lower,10.0
4,ed,philo,Male,1991-05-14,24,0,4,0,1,4,-1.0,10.0,1.0,1.0,0.0,2013-06-16,2013-06-16,0,NaN,NaT,Low,2013-04-14,3,Low,0,Lower,1.0
9,marcu,brown,Male,1993-01-21,23,0,8,1,0,1,NaN,10.0,0.0,NaN,NaN,NaT,NaT,0,NaN,NaT,High,2013-01-13,6,Medium,0,Lower,NaN
10,bouthy,pierrelouis,Male,1973-01-22,43,0,1,0,0,2,NaN,16.0,0.0,NaN,NaN,NaT,NaT,0,NaN,NaT,Low,2013-03-26,1,Low,0,Lower,NaN
11,marsha,miles,Male,1971-08-22,44,0,1,0,0,0,0.0,1.0,0.0,NaN,NaN,NaT,NaT,0,NaN,NaT,Low,2013-11-30,1,Low,0,Lower,1.0
12,edward,riddle,Male,1974-07-23,41,0,6,0,0,14,-1.0,10.0,1.0,8.0,0.0,2014-03-31,2014-03-31,0,NaN,NaT,Medium,2014-02-19,2,Low,0,Lower,6.0

# Step2. Processing compas-scores-raw dataset

In [11]:
## This database contains additional useful variables for predicting decile scores
csr_df = pd.read_csv('datasets/compas-scores-raw.csv')
csr_df.head()

,Person_ID,AssessmentID,Case_ID,Agency_Text,LastName,FirstName,MiddleName,Sex_Code_Text,Ethnic_Code_Text,DateOfBirth,ScaleSet_ID,ScaleSet,AssessmentReason,Language,LegalStatus,CustodyStatus,MaritalStatus,Screening_Date,RecSupervisionLevel,RecSupervisionLevelText,Scale_ID,DisplayText,RawScore,DecileScore,ScoreText,AssessmentType,IsCompleted,IsDeleted
0,50844,57167,51950,PRETRIAL,Fisher,Kevin,NaN,Male,Caucasian,12/05/92,22,Risk and Prescreen,Intake,English,Pretrial,Jail Inmate,Single,1/1/13 0:00,1,Low,7,Risk of Violence,-2.08,4,Low,New,1,0
1,50844,57167,51950,PRETRIAL,Fisher,Kevin,NaN,Male,Caucasian,12/05/92,22,Risk and Prescreen,Intake,English,Pretrial,Jail Inmate,Single,1/1/13 0:00,1,Low,8,Risk of Recidivism,-1.06,2,Low,New,1,0
2,50844,57167,51950,PRETRIAL,Fisher,Kevin,NaN,Male,Caucasian,12/05/92,22,Risk and Prescreen,Intake,English,Pretrial,Jail Inmate,Single,1/1/13 0:00,1,Low,18,Risk of Failure to Appear,15.00,1,Low,New,1,0
3,50848,57174,51956,PRETRIAL,KENDALL,KEVIN,NaN,Male,Caucasian,09/16/84,22,Risk and Prescreen,Intake,English,Pretrial,Jail Inmate,Married,1/1/13 0:00,1,Low,7,Risk of Violence,-2.84,2,Low,New,1,0
4,50848,57174,51956,PRETRIAL,KENDALL,KEVIN,NaN,Male,Caucasian,09/16/84,22,Risk and Prescreen,Intake,English,Pretrial,Jail Inmate,Married,1/1/13 0:00,1,Low,8,Risk of Recidivism,-1.50,1,Low,New,1,0

In [12]:
## Extracting different risk scores as independent columns
csr_df['RiskOfViolence_RawScore'] = csr_df.apply(lambda row: row.RawScore if row.Scale_ID == 7 else np.nan, axis=1)
csr_df['RiskOfViolence_DecileScore'] = csr_df.apply(lambda row: row.DecileScore if row.Scale_ID == 7 else np.nan, axis=1)
csr_df['RiskOfViolence_ScoreText'] = csr_df.apply(lambda row: row.ScoreText if row.Scale_ID == 7 else np.nan, axis=1)

csr_df['RiskOfRecidivism_RawScore'] = csr_df.apply(lambda row: row.RawScore if row.Scale_ID == 8 else np.nan, axis=1)
csr_df['RiskOfRecidivism_DecileScore'] = csr_df.apply(lambda row: row.DecileScore if row.Scale_ID == 8 else np.nan, axis=1)
csr_df['RiskOfRecidivism_ScoreText'] = csr_df.apply(lambda row: row.ScoreText if row.Scale_ID == 8 else np.nan, axis=1)

csr_df['RiskOfFailureToAppear_RawScore'] = csr_df.apply(lambda row: row.RawScore if row.Scale_ID == 18 else np.nan, axis=1)
csr_df['RiskOfFailureToAppear_DecileScore'] = csr_df.apply(lambda row: row.DecileScore if row.Scale_ID == 18 else np.nan, axis=1)
csr_df['RiskOfFailureToAppear_ScoreText'] = csr_df.apply(lambda row: row.ScoreText if row.Scale_ID == 18 else np.nan, axis=1)

In [13]:
csr_df.head(8)

,Person_ID,AssessmentID,Case_ID,Agency_Text,LastName,FirstName,MiddleName,Sex_Code_Text,Ethnic_Code_Text,DateOfBirth,ScaleSet_ID,ScaleSet,AssessmentReason,Language,LegalStatus,CustodyStatus,MaritalStatus,Screening_Date,RecSupervisionLevel,RecSupervisionLevelText,Scale_ID,DisplayText,RawScore,DecileScore,ScoreText,AssessmentType,IsCompleted,IsDeleted,RiskOfViolence_RawScore,RiskOfViolence_DecileScore,RiskOfViolence_ScoreText,RiskOfRecidivism_RawScore,RiskOfRecidivism_DecileScore,RiskOfRecidivism_ScoreText,RiskOfFailureToAppear_RawScore,RiskOfFailureToAppear_DecileScore,RiskOfFailureToAppear_ScoreText
0,50844,57167,51950,PRETRIAL,Fisher,Kevin,NaN,Male,Caucasian,12/05/92,22,Risk and Prescreen,Intake,English,Pretrial,Jail Inmate,Single,1/1/13 0:00,1,Low,7,Risk of Violence,-2.08,4,Low,New,1,0,-2.08,4.0,Low,NaN,NaN,NaN,NaN,NaN,NaN
1,50844,57167,51950,PRETRIAL,Fisher,Kevin,NaN,Male,Caucasian,12/05/92,22,Risk and Prescreen,Intake,English,Pretrial,Jail Inmate,Single,1/1/13 0:00,1,Low,8,Risk of Recidivism,-1.06,2,Low,New,1,0,NaN,NaN,NaN,-1.06,2.0,Low,NaN,NaN,NaN
2,50844,57167,51950,PRETRIAL,Fisher,Kevin,NaN,Male,Caucasian,12/05/92,22,Risk and Prescreen,Intake,English,Pretrial,Jail Inmate,Single,1/1/13 0:00,1,Low,18,Risk of Failure to Appear,15.00,1,Low,New,1,0,NaN,NaN,NaN,NaN,NaN,NaN,15.0,1.0,Low
3,50848,57174,51956,PRETRIAL,KENDALL,KEVIN,NaN,Male,Caucasian,09/16/84,22,Risk and Prescreen,Intake,English,Pretrial,Jail Inmate,Married,1/1/13 0:00,1,Low,7,Risk of Violence,-2.84,2,Low,New,1,0,-2.84,2.0,Low,NaN,NaN,NaN,NaN,NaN,NaN
4,50848,57174,51956,PRETRIAL,KENDALL,KEVIN,NaN,Male,Caucasian,09/16/84,22,Risk and Prescreen,Intake,English,Pretrial,Jail Inmate,Married,1/1/13 0:00,1,Low,8,Risk of Recidivism,-1.50,1,Low,New,1,0,NaN,NaN,NaN,-1.50,1.0,Low,NaN,NaN,NaN
5,50848,57174,51956,PRETRIAL,KENDALL,KEVIN,NaN,Male,Caucasian,09/16/84,22,Risk and Prescreen,Intake,English,Pretrial,Jail Inmate,Married,1/1/13 0:00,1,Low,18,Risk of Failure to Appear,19.00,3,Low,New,1,0,NaN,NaN,NaN,NaN,NaN,NaN,19.0,3.0,Low
6,50855,57181,51963,PRETRIAL,DAYES,DANIEL,NaN,Male,African-American,08/25/94,22,Risk and Prescreen,Intake,English,Pretrial,Jail Inmate,Single,1/1/13 0:00,4,High,7,Risk of Violence,-1.20,8,High,New,1,0,-1.20,8.0,High,NaN,NaN,NaN,NaN,NaN,NaN
7,50855,57181,51963,PRETRIAL,DAYES,DANIEL,NaN,Male,African-American,08/25/94,22,Risk and Prescreen,Intake,English,Pretrial,Jail Inmate,Single,1/1/13 0:00,4,High,8,Risk of Recidivism,0.18,8,High,New,1,0,NaN,NaN,NaN,0.18,8.0,High,NaN,NaN,NaN

In [14]:
## Merging duplicate rows
repeated_columns = ['Person_ID','Agency_Text','LastName','FirstName','DateOfBirth','LegalStatus',
                    'CustodyStatus','MaritalStatus','RecSupervisionLevel','RecSupervisionLevelText']

risk_columns = ['RiskOfViolence_RawScore','RiskOfViolence_DecileScore','RiskOfViolence_ScoreText',
                'RiskOfRecidivism_RawScore','RiskOfRecidivism_DecileScore','RiskOfRecidivism_ScoreText',
                'RiskOfFailureToAppear_RawScore','RiskOfFailureToAppear_DecileScore','RiskOfFailureToAppear_ScoreText']

agg_dict = {col: 'first' for col in risk_columns}
csr_df = csr_df.groupby(repeated_columns).agg(agg_dict).reset_index()

In [15]:
csr_df['DateOfBirth'] = pd.to_datetime(csr_df['DateOfBirth'], format='%m/%d/%y')
csr_df['LastName'] = csr_df['LastName'].str.lower()
csr_df['FirstName'] = csr_df['FirstName'].str.lower()

csr_df.drop('Person_ID', axis=1, inplace=True)

In [16]:
csr_df[csr_df['LastName'] == 'philo']

,Agency_Text,LastName,FirstName,DateOfBirth,LegalStatus,CustodyStatus,MaritalStatus,RecSupervisionLevel,RecSupervisionLevelText,RiskOfViolence_RawScore,RiskOfViolence_DecileScore,RiskOfViolence_ScoreText,RiskOfRecidivism_RawScore,RiskOfRecidivism_DecileScore,RiskOfRecidivism_ScoreText,RiskOfFailureToAppear_RawScore,RiskOfFailureToAppear_DecileScore,RiskOfFailureToAppear_ScoreText
2379,PRETRIAL,philo,ed,1991-05-14,Pretrial,Jail Inmate,Single,1,Low,-2.26,3.0,Low,-0.66,4.0,Low,26.0,7.0,Medium
11595,Probation,philo,ed,1991-05-14,Conditional Release,Probation,Single,3,Medium with Override Consideration,-1.31,7.0,Medium,0.44,9.0,High,25.0,5.0,Medium
11596,Probation,philo,ed,1991-05-14,Post Sentence,Probation,Single,3,Medium with Override Consideration,-1.27,7.0,Medium,0.49,9.0,High,28.0,8.0,High

# Step3. Combining cvp_df with csr_df

In [17]:
## final data frame (fdf)
fdf = pd.merge(cvp_df, csr_df, left_on=['first', 'last', 'dob'], right_on=['FirstName', 'LastName', 'DateOfBirth'], how='inner')
fdf.drop(['first', 'last', 'dob'], axis=1, inplace=True)

In [18]:
print(fdf.shape)
print(fdf[['LastName', 'FirstName', 'DateOfBirth']].drop_duplicates().shape[0])

(9543, 42)
8489

# Step4: Imputing missing values for mixed-type data

In [19]:
# Check missing values:

print(fdf.isnull().sum())

sex                                     0
age                                     0
juv_fel_count                           0
decile_score                            0
juv_misd_count                          0
juv_other_count                         0
priors_count                            0
days_b_screening_arrest               826
c_charge_degree                       532
is_recid                              507
r_charge_degree                      5911
r_days_from_arrest                   7041
r_offense_date                       5909
r_jail_in                            7041
is_violent_recid                        0
vr_charge_degree                     8400
vr_offense_date                      8400
score_text                              7
screening_date                          0
v_decile_score                          0
v_score_text                            1
event                                   0
income                                  0
jail_duration                         826
Agency_Text                             0
LastName                                0
FirstName                               0
DateOfBirth                             0
LegalStatus                             0
CustodyStatus                           0
MaritalStatus                           0
RecSupervisionLevel                     0
RecSupervisionLevelText                 0
RiskOfViolence_RawScore                 0
RiskOfViolence_DecileScore              0
RiskOfViolence_ScoreText                1
RiskOfRecidivism_RawScore               0
RiskOfRecidivism_DecileScore            0
RiskOfRecidivism_ScoreText              6
RiskOfFailureToAppear_RawScore          0
RiskOfFailureToAppear_DecileScore       0
RiskOfFailureToAppear_ScoreText         0
dtype: int64

### Imputing numerical columns

In [20]:
#following line not needed if on colab
%pip install scikit-learn -q
# To impute numerical columns we use Mean/Median Imputation
# Identify numeric columns (excluding categorical)
numeric_cols = fdf.select_dtypes(include=['number']).columns

# Initialize the imputer
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy='median')  # i used the median

# Apply imputation
fdf[numeric_cols] = imputer.fit_transform(fdf[numeric_cols])

Note: you may need to restart the kernel to use updated packages.

In [21]:
# Check missing values after imputing the numerical columns:

print(fdf.isnull().sum())

sex                                     0
age                                     0
juv_fel_count                           0
decile_score                            0
juv_misd_count                          0
juv_other_count                         0
priors_count                            0
days_b_screening_arrest                 0
c_charge_degree                         0
is_recid                                0
r_charge_degree                         0
r_days_from_arrest                      0
r_offense_date                       5909
r_jail_in                            7041
is_violent_recid                        0
vr_charge_degree                        0
vr_offense_date                      8400
score_text                              7
screening_date                          0
v_decile_score                          0
v_score_text                            1
event                                   0
income                                  0
jail_duration                           0
Agency_Text                             0
LastName                                0
FirstName                               0
DateOfBirth                             0
LegalStatus                             0
CustodyStatus                           0
MaritalStatus                           0
RecSupervisionLevel                     0
RecSupervisionLevelText                 0
RiskOfViolence_RawScore                 0
RiskOfViolence_DecileScore              0
RiskOfViolence_ScoreText                1
RiskOfRecidivism_RawScore               0
RiskOfRecidivism_DecileScore            0
RiskOfRecidivism_ScoreText              6
RiskOfFailureToAppear_RawScore          0
RiskOfFailureToAppear_DecileScore       0
RiskOfFailureToAppear_ScoreText         0
dtype: int64

# Imputing categorical values

In [22]:
# Risk score we have (Low, Medium, High)
# Violent risk score (Low, Medium, High)
mode_cols = ["score_text","v_score_text", "RiskOfViolence_ScoreText","RiskOfRecidivism_ScoreText"]
for col in mode_cols:
    fdf[col].fillna(fdf[col].mode()[0], inplace=True)

# Date of prior offense, date of prior jail entry, and date of violent offense
    unknown_cols = [ "r_offense_date","r_jail_in","vr_offense_date"]

for col in unknown_cols:
    fdf[col].fillna("Unknown", inplace=True)

C:\Users\wissa\AppData\Local\Temp\ipykernel_24216\263880281.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  fdf[col].fillna(fdf[col].mode()[0], inplace=True)
C:\Users\wissa\AppData\Local\Temp\ipykernel_24216\263880281.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  fdf[col].fillna("Unknown", inplace=True)
C:\Users\wissa\AppData\Local\Temp\ipykernel_24216\263880281.py:11: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Unknown' has dtype incompatible with datetime64[ns], please explicitly cast to a compatible dtype first.
  fdf[col].fillna("Unknown", inplace=True)

In [23]:
# check if there are any categorical missing values
print(fdf.isnull().sum())

sex                                  0
age                                  0
juv_fel_count                        0
decile_score                         0
juv_misd_count                       0
juv_other_count                      0
priors_count                         0
days_b_screening_arrest              0
c_charge_degree                      0
is_recid                             0
r_charge_degree                      0
r_days_from_arrest                   0
r_offense_date                       0
r_jail_in                            0
is_violent_recid                     0
vr_charge_degree                     0
vr_offense_date                      0
score_text                           0
screening_date                       0
v_decile_score                       0
v_score_text                         0
event                                0
income                               0
jail_duration                        0
Agency_Text                          0
LastName                             0
FirstName                            0
DateOfBirth                          0
LegalStatus                          0
CustodyStatus                        0
MaritalStatus                        0
RecSupervisionLevel                  0
RecSupervisionLevelText              0
RiskOfViolence_RawScore              0
RiskOfViolence_DecileScore           0
RiskOfViolence_ScoreText             0
RiskOfRecidivism_RawScore            0
RiskOfRecidivism_DecileScore         0
RiskOfRecidivism_ScoreText           0
RiskOfFailureToAppear_RawScore       0
RiskOfFailureToAppear_DecileScore    0
RiskOfFailureToAppear_ScoreText      0
dtype: int64

In [24]:
print((fdf['FirstName'] + ' ' + fdf['LastName']).nunique())
fdf.count()
## Todo: deal with multiple records from the same person.

8422

sex                                  9543
age                                  9543
juv_fel_count                        9543
decile_score                         9543
juv_misd_count                       9543
juv_other_count                      9543
priors_count                         9543
days_b_screening_arrest              9543
c_charge_degree                      9543
is_recid                             9543
r_charge_degree                      9543
r_days_from_arrest                   9543
r_offense_date                       9543
r_jail_in                            9543
is_violent_recid                     9543
vr_charge_degree                     9543
vr_offense_date                      9543
score_text                           9543
screening_date                       9543
v_decile_score                       9543
v_score_text                         9543
event                                9543
income                               9543
jail_duration                        9543
Agency_Text                          9543
LastName                             9543
FirstName                            9543
DateOfBirth                          9543
LegalStatus                          9543
CustodyStatus                        9543
MaritalStatus                        9543
RecSupervisionLevel                  9543
RecSupervisionLevelText              9543
RiskOfViolence_RawScore              9543
RiskOfViolence_DecileScore           9543
RiskOfViolence_ScoreText             9543
RiskOfRecidivism_RawScore            9543
RiskOfRecidivism_DecileScore         9543
RiskOfRecidivism_ScoreText           9543
RiskOfFailureToAppear_RawScore       9543
RiskOfFailureToAppear_DecileScore    9543
RiskOfFailureToAppear_ScoreText      9543
dtype: int64

### Download section

In [25]:
## Save the modified dataset
csv_filename = "datasets/final-preprocessed-imputed-compas-df.csv"
fdf.to_csv(csv_filename, index=False)

In [26]:
## Downloading the file
try:
    from google.colab import files
    files.download(csv_filename)
except ImportError:
    print(f"Download manually from your working directory: {csv_filename}")

Download manually from your working directory: datasets/final-preprocessed-imputed-compas-df.csv